export { createSpatialContext } from './context.js'
export {
  buildTerrainAwareFlightPlan,
  densifyFlightRoute,
} from './flight-planning.js'
export {
  boundsContain,
  boundsIntersect,
  coordinatesBounds,
  geometryBounds,
  geometryCentroid,
  haversineDistanceMeters,
  mergeBounds,
  pointInPolygon,
} from './geometry.js'
export * from './world-awareness/index.js'
export {
  COMMUNITY_OBJECT_ID,
  createEmergencyResponseFeatures,
  createEmergencyResponseGeoJson,
  createEmergencyResponseObjects,
  EMERGENCY_VIEW_BOUNDS,
  emergencyQueryCases,
  emergencyRelationCases,
  FLOOD_BASELINE_RING,
  FLOOD_EXPANDED_RING,
  FLOOD_OBJECT_ID,
  HOSPITAL_OBJECT_ID,
  PRIMARY_ROUTE_OBJECT_ID,
  PUMP_STATION_OBJECT_ID,
  runEmergencyResponseEvaluation,
  SCENE_LAYER_ID,
  SCENE_RESOURCE_ID,
  SCHOOL_OBJECT_ID,
  SCHOOL_POSITION,
  SHELTER_OBJECT_ID,
} from './evals/emergency-response.js'
export type {
  EmergencyEvaluationAssertion,
  EmergencyEvaluationReport,
  EmergencyEvaluationStageReport,
  EmergencyResponseFeature,
  EmergencyResponseGeoJson,
  EmergencyResponseStage,
  SpatialQueryEvaluationCase,
  SpatialRelationEvaluationCase,
} from './evals/emergency-response.js'
export {
  HIDDEN_CORRIDOR_FIXTURES,
  HIDDEN_CORRIDOR_REGION_IDS,
  createHiddenCorridorFixtures,
} from './evals/hidden-corridor-fixtures.js'
export type {
  HiddenCorridorActualCandidateCoverage,
  HiddenCorridorActualObservationAttempt,
  HiddenCorridorActualRegionCoverage,
  HiddenCorridorCaseId,
  HiddenCorridorCell,
  HiddenCorridorExpectedOutcome,
  HiddenCorridorFixture,
  HiddenCorridorId,
  HiddenCorridorOracleFixture,
  HiddenCorridorPlannerFixture,
  HiddenCorridorRevisionEvent,
  HiddenCorridorRoute,
} from './evals/hidden-corridor-fixtures.js'
export {
  buildHiddenCorridorTopology,
  createHiddenCorridorPolicyBelief,
  createHiddenCorridorPolicyContext,
  runHiddenCorridorCase,
  runHiddenCorridorEvaluation,
  selectHiddenCorridorObservation,
} from './evals/hidden-corridor.js'
export type {
  HiddenCorridorCaseReport,
  HiddenCorridorEvaluationReport,
  HiddenCorridorEvaluationSummary,
  HiddenCorridorPolicyContext,
  HiddenCorridorRoutePlanRecord,
  HiddenCorridorRunMetrics,
  HiddenCorridorRunReport,
  HiddenCorridorStrategyId,
} from './evals/hidden-corridor.js'
export type {
  FlightRouteCoordinate,
  FlightTerrainSample,
  SpatialBounds,
  SpatialContext,
  SpatialContextSummary,
  SpatialCoordinate,
  SpatialEvidenceQuality,
  SpatialGeometry,
  SpatialNearQuery,
  SpatialObject,
  SpatialObjectProvenance,
  SpatialObjectQuery,
  SpatialRelation,
  SpatialRelationOptions,
  SpatialRelationResult,
  SpatialSourceType,
  TerrainAwareFlightMetrics,
  TerrainAwareFlightOptions,
  TerrainAwareFlightPlan,
  TerrainAwareFlightSample,
} from './types.js'
